name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and analyze
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: cd java && ./gradlew test jacocoTestReport && curl https://deepsource.io/cli | sh && ./bin/deepsource report --analyzer test-coverage --key java --value-file ./multiModule1/subMultiModule1/build/reports/jacoco/test/jacocoTestReport.xml
